### ISSUE TITLE
Anpassen der Schriftgröße und Zeichen (z.B. Sigma / Summe) von Formeln

### ISSUE THREAD

**Issue by lwarode** [lwarode/Formelsammlung_Statistik#2]
LaTeX Code in .Rmd header (header-includes) mit \DeclareMathSizes scheint nur teilweise zu funktionieren und ignoriert Symbole/Zeichen wie Sigma

**Comment by christine-hvw** [comment]
Konnte ich nicht global lösen.
Drei Möglichkeiten:
1. im header declaremathsizes: Sigma ist dann etwas kleiner, ist aber noch im Rahmen finde ich
2. in jeder formel \large am Anfang: kann man nicht global festlegen **rendert aber auch in html** !
3. nichts anpassen: Formeln bleiben so groß wie Schriftgröße

Wäre stark für 2.

**Comment by lwarode** [comment]
Finde 2 auch gut, vor allem wenn Kompatibilität zu HTML gegeben ist
